// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spotify_migration/entities/data"

	mock "github.com/stretchr/testify/mock"
)

// NewIGetAlbums creates a new instance of IGetAlbums. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetAlbums(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetAlbums {
	mock := &IGetAlbums{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IGetAlbums is an autogenerated mock type for the IGetAlbums type
type IGetAlbums struct {
	mock.Mock
}

type IGetAlbums_Expecter struct {
	mock *mock.Mock
}

func (_m *IGetAlbums) EXPECT() *IGetAlbums_Expecter {
	return &IGetAlbums_Expecter{mock: &_m.Mock}
}

// GetAlbums provides a mock function for the type IGetAlbums
func (_mock *IGetAlbums) GetAlbums(ctx context.Context) (*data.Collection, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbums")
	}

	var r0 *data.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*data.Collection, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *data.Collection); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*data.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IGetAlbums_GetAlbums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbums'
type IGetAlbums_GetAlbums_Call struct {
	*mock.Call
}

// GetAlbums is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IGetAlbums_Expecter) GetAlbums(ctx interface{}) *IGetAlbums_GetAlbums_Call {
	return &IGetAlbums_GetAlbums_Call{Call: _e.mock.On("GetAlbums", ctx)}
}

func (_c *IGetAlbums_GetAlbums_Call) Run(run func(ctx context.Context)) *IGetAlbums_GetAlbums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IGetAlbums_GetAlbums_Call) Return(albums *data.Collection, err error) *IGetAlbums_GetAlbums_Call {
	_c.Call.Return(albums, err)
	return _c
}

func (_c *IGetAlbums_GetAlbums_Call) RunAndReturn(run func(ctx context.Context) (*data.Collection, error)) *IGetAlbums_GetAlbums_Call {
	_c.Call.Return(run)
	return _c
}
