// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spotify_migration/entities/data"

	mock "github.com/stretchr/testify/mock"
)

// NewIGetAlbuns creates a new instance of IGetAlbuns. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGetAlbuns(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGetAlbuns {
	mock := &IGetAlbuns{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IGetAlbuns is an autogenerated mock type for the IGetAlbuns type
type IGetAlbuns struct {
	mock.Mock
}

type IGetAlbuns_Expecter struct {
	mock *mock.Mock
}

func (_m *IGetAlbuns) EXPECT() *IGetAlbuns_Expecter {
	return &IGetAlbuns_Expecter{mock: &_m.Mock}
}

// GetAlbuns provides a mock function for the type IGetAlbuns
func (_mock *IGetAlbuns) GetAlbuns(ctx context.Context) ([]*data.Album, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAlbuns")
	}

	var r0 []*data.Album
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*data.Album, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*data.Album); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*data.Album)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IGetAlbuns_GetAlbuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlbuns'
type IGetAlbuns_GetAlbuns_Call struct {
	*mock.Call
}

// GetAlbuns is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IGetAlbuns_Expecter) GetAlbuns(ctx interface{}) *IGetAlbuns_GetAlbuns_Call {
	return &IGetAlbuns_GetAlbuns_Call{Call: _e.mock.On("GetAlbuns", ctx)}
}

func (_c *IGetAlbuns_GetAlbuns_Call) Run(run func(ctx context.Context)) *IGetAlbuns_GetAlbuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *IGetAlbuns_GetAlbuns_Call) Return(albuns []*data.Album, err error) *IGetAlbuns_GetAlbuns_Call {
	_c.Call.Return(albuns, err)
	return _c
}

func (_c *IGetAlbuns_GetAlbuns_Call) RunAndReturn(run func(ctx context.Context) ([]*data.Album, error)) *IGetAlbuns_GetAlbuns_Call {
	_c.Call.Return(run)
	return _c
}
