// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewIMigrate creates a new instance of IMigrate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMigrate(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMigrate {
	mock := &IMigrate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IMigrate is an autogenerated mock type for the IMigrate type
type IMigrate struct {
	mock.Mock
}

type IMigrate_Expecter struct {
	mock *mock.Mock
}

func (_m *IMigrate) EXPECT() *IMigrate_Expecter {
	return &IMigrate_Expecter{mock: &_m.Mock}
}

// Migrate provides a mock function for the type IMigrate
func (_mock *IMigrate) Migrate(ctx context.Context, resourceName string) (bool, error) {
	ret := _mock.Called(ctx, resourceName)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, resourceName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, resourceName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, resourceName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IMigrate_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type IMigrate_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceName string
func (_e *IMigrate_Expecter) Migrate(ctx interface{}, resourceName interface{}) *IMigrate_Migrate_Call {
	return &IMigrate_Migrate_Call{Call: _e.mock.On("Migrate", ctx, resourceName)}
}

func (_c *IMigrate_Migrate_Call) Run(run func(ctx context.Context, resourceName string)) *IMigrate_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IMigrate_Migrate_Call) Return(b bool, err error) *IMigrate_Migrate_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *IMigrate_Migrate_Call) RunAndReturn(run func(ctx context.Context, resourceName string) (bool, error)) *IMigrate_Migrate_Call {
	_c.Call.Return(run)
	return _c
}
