// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spotify_migration/entities/data"

	mock "github.com/stretchr/testify/mock"
)

// NewISaveAlbums creates a new instance of ISaveAlbums. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISaveAlbums(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISaveAlbums {
	mock := &ISaveAlbums{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ISaveAlbums is an autogenerated mock type for the ISaveAlbums type
type ISaveAlbums struct {
	mock.Mock
}

type ISaveAlbums_Expecter struct {
	mock *mock.Mock
}

func (_m *ISaveAlbums) EXPECT() *ISaveAlbums_Expecter {
	return &ISaveAlbums_Expecter{mock: &_m.Mock}
}

// SaveAlbums provides a mock function for the type ISaveAlbums
func (_mock *ISaveAlbums) SaveAlbums(ctx context.Context, albums []*data.Album) error {
	ret := _mock.Called(ctx, albums)

	if len(ret) == 0 {
		panic("no return value specified for SaveAlbums")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*data.Album) error); ok {
		r0 = returnFunc(ctx, albums)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ISaveAlbums_SaveAlbums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAlbums'
type ISaveAlbums_SaveAlbums_Call struct {
	*mock.Call
}

// SaveAlbums is a helper method to define mock.On call
//   - ctx context.Context
//   - albums []*data.Album
func (_e *ISaveAlbums_Expecter) SaveAlbums(ctx interface{}, albums interface{}) *ISaveAlbums_SaveAlbums_Call {
	return &ISaveAlbums_SaveAlbums_Call{Call: _e.mock.On("SaveAlbums", ctx, albums)}
}

func (_c *ISaveAlbums_SaveAlbums_Call) Run(run func(ctx context.Context, albums []*data.Album)) *ISaveAlbums_SaveAlbums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*data.Album
		if args[1] != nil {
			arg1 = args[1].([]*data.Album)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ISaveAlbums_SaveAlbums_Call) Return(err error) *ISaveAlbums_SaveAlbums_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ISaveAlbums_SaveAlbums_Call) RunAndReturn(run func(ctx context.Context, albums []*data.Album) error) *ISaveAlbums_SaveAlbums_Call {
	_c.Call.Return(run)
	return _c
}
