// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"spotify_migration/entities/data"

	mock "github.com/stretchr/testify/mock"
)

// NewISaveAlbuns creates a new instance of ISaveAlbuns. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISaveAlbuns(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISaveAlbuns {
	mock := &ISaveAlbuns{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ISaveAlbuns is an autogenerated mock type for the ISaveAlbuns type
type ISaveAlbuns struct {
	mock.Mock
}

type ISaveAlbuns_Expecter struct {
	mock *mock.Mock
}

func (_m *ISaveAlbuns) EXPECT() *ISaveAlbuns_Expecter {
	return &ISaveAlbuns_Expecter{mock: &_m.Mock}
}

// SaveAlbuns provides a mock function for the type ISaveAlbuns
func (_mock *ISaveAlbuns) SaveAlbuns(ctx context.Context, albums []*data.Album) error {
	ret := _mock.Called(ctx, albums)

	if len(ret) == 0 {
		panic("no return value specified for SaveAlbuns")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*data.Album) error); ok {
		r0 = returnFunc(ctx, albums)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ISaveAlbuns_SaveAlbuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAlbuns'
type ISaveAlbuns_SaveAlbuns_Call struct {
	*mock.Call
}

// SaveAlbuns is a helper method to define mock.On call
//   - ctx context.Context
//   - albums []*data.Album
func (_e *ISaveAlbuns_Expecter) SaveAlbuns(ctx interface{}, albums interface{}) *ISaveAlbuns_SaveAlbuns_Call {
	return &ISaveAlbuns_SaveAlbuns_Call{Call: _e.mock.On("SaveAlbuns", ctx, albums)}
}

func (_c *ISaveAlbuns_SaveAlbuns_Call) Run(run func(ctx context.Context, albums []*data.Album)) *ISaveAlbuns_SaveAlbuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*data.Album
		if args[1] != nil {
			arg1 = args[1].([]*data.Album)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ISaveAlbuns_SaveAlbuns_Call) Return(err error) *ISaveAlbuns_SaveAlbuns_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ISaveAlbuns_SaveAlbuns_Call) RunAndReturn(run func(ctx context.Context, albums []*data.Album) error) *ISaveAlbuns_SaveAlbuns_Call {
	_c.Call.Return(run)
	return _c
}
