// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewITargetCollection creates a new instance of ITargetCollection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITargetCollection(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITargetCollection {
	mock := &ITargetCollection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ITargetCollection is an autogenerated mock type for the ITargetCollection type
type ITargetCollection struct {
	mock.Mock
}

type ITargetCollection_Expecter struct {
	mock *mock.Mock
}

func (_m *ITargetCollection) EXPECT() *ITargetCollection_Expecter {
	return &ITargetCollection_Expecter{mock: &_m.Mock}
}

// CheckIfCollectionExists provides a mock function for the type ITargetCollection
func (_mock *ITargetCollection) CheckIfCollectionExists(ctx context.Context, playlistName string) (string, error) {
	ret := _mock.Called(ctx, playlistName)

	if len(ret) == 0 {
		panic("no return value specified for CheckIfCollectionExists")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, playlistName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, playlistName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, playlistName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITargetCollection_CheckIfCollectionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckIfCollectionExists'
type ITargetCollection_CheckIfCollectionExists_Call struct {
	*mock.Call
}

// CheckIfCollectionExists is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistName string
func (_e *ITargetCollection_Expecter) CheckIfCollectionExists(ctx interface{}, playlistName interface{}) *ITargetCollection_CheckIfCollectionExists_Call {
	return &ITargetCollection_CheckIfCollectionExists_Call{Call: _e.mock.On("CheckIfCollectionExists", ctx, playlistName)}
}

func (_c *ITargetCollection_CheckIfCollectionExists_Call) Run(run func(ctx context.Context, playlistName string)) *ITargetCollection_CheckIfCollectionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ITargetCollection_CheckIfCollectionExists_Call) Return(collectionID string, err error) *ITargetCollection_CheckIfCollectionExists_Call {
	_c.Call.Return(collectionID, err)
	return _c
}

func (_c *ITargetCollection_CheckIfCollectionExists_Call) RunAndReturn(run func(ctx context.Context, playlistName string) (string, error)) *ITargetCollection_CheckIfCollectionExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCollection provides a mock function for the type ITargetCollection
func (_mock *ITargetCollection) CreateCollection(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateCollection")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ITargetCollection_CreateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCollection'
type ITargetCollection_CreateCollection_Call struct {
	*mock.Call
}

// CreateCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *ITargetCollection_Expecter) CreateCollection(ctx interface{}, name interface{}) *ITargetCollection_CreateCollection_Call {
	return &ITargetCollection_CreateCollection_Call{Call: _e.mock.On("CreateCollection", ctx, name)}
}

func (_c *ITargetCollection_CreateCollection_Call) Run(run func(ctx context.Context, name string)) *ITargetCollection_CreateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ITargetCollection_CreateCollection_Call) Return(collectionID string, err error) *ITargetCollection_CreateCollection_Call {
	_c.Call.Return(collectionID, err)
	return _c
}

func (_c *ITargetCollection_CreateCollection_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *ITargetCollection_CreateCollection_Call {
	_c.Call.Return(run)
	return _c
}
