// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewITargetWriter creates a new instance of ITargetWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITargetWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITargetWriter {
	mock := &ITargetWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ITargetWriter is an autogenerated mock type for the ITargetWriter type
type ITargetWriter struct {
	mock.Mock
}

type ITargetWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *ITargetWriter) EXPECT() *ITargetWriter_Expecter {
	return &ITargetWriter_Expecter{mock: &_m.Mock}
}

// AddItemToPlaylist provides a mock function for the type ITargetWriter
func (_mock *ITargetWriter) AddItemToPlaylist(ctx context.Context, collectionID string, itemID string) error {
	ret := _mock.Called(ctx, collectionID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for AddItemToPlaylist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, collectionID, itemID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ITargetWriter_AddItemToPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddItemToPlaylist'
type ITargetWriter_AddItemToPlaylist_Call struct {
	*mock.Call
}

// AddItemToPlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionID string
//   - itemID string
func (_e *ITargetWriter_Expecter) AddItemToPlaylist(ctx interface{}, collectionID interface{}, itemID interface{}) *ITargetWriter_AddItemToPlaylist_Call {
	return &ITargetWriter_AddItemToPlaylist_Call{Call: _e.mock.On("AddItemToPlaylist", ctx, collectionID, itemID)}
}

func (_c *ITargetWriter_AddItemToPlaylist_Call) Run(run func(ctx context.Context, collectionID string, itemID string)) *ITargetWriter_AddItemToPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ITargetWriter_AddItemToPlaylist_Call) Return(err error) *ITargetWriter_AddItemToPlaylist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ITargetWriter_AddItemToPlaylist_Call) RunAndReturn(run func(ctx context.Context, collectionID string, itemID string) error) *ITargetWriter_AddItemToPlaylist_Call {
	_c.Call.Return(run)
	return _c
}
